import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorProvider } from "@/lib/context/colorContext";
import { SpaceProvider } from "@/lib/context/spaceContext";
import { RadiusProvider } from "@/lib/context/radiusContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorProvider>
          <SpaceProvider>
            <RadiusProvider>{children}</RadiusProvider>
          </SpaceProvider>
        </ColorProvider>
      </body>
    </html>
  );
}
